### ISSUE TITLE
Bug in emscripten JS bindings

### ISSUE THREAD

**Issue by Kipples** [CryZe/livesplit-core#51]
LiveSplitCore is not defined.
Looks like something changed for the typescript bindings but didn't get changed for the JS bindings.

**Comment by CryZe** [comment]
Oh yeah, looks like you are right. I'll fix it later today. May I ask what you are using it for? :)

**Comment by Kipples** [comment]
thanks,

I am currently just testing ls-core to see if I can use it to make a timer using clojurescript and electron.

**Comment by CryZe** [comment]
Ah, that's cool. While I would love people to write timers with livesplit-core, I would like to ask you if the use case is different enough from LiveSplit One which is a React based front end + Electron to livesplit-core. So that's very similar to what you are trying to do. If it's just for experimenting around, that's fine. If it has entirely different goals, like being a much more streamlined and simpler timer with less clutter (maybe no game time, no or less comparisons, ...), then that's also a perfectly good goal to have. However if our goals are too similar, it may make more sense to help us with LiveSplit One instead.

**Comment by CryZe** [comment]
This is also resolved now. I'll keep this open until your response though.

**Comment by Kipples** [comment]
Thanks,

at the moment I am just testing and experimenting no real plans.
