### ISSUE TITLE
Timer.current_time method is not available in the npm package

### ISSUE THREAD

**Issue by Lange** [CryZe/livesplit-core#79]
Hello! :wave:

I'm evaluating implementing `livesplit-core` in the GDQ graphics system. This system is a Node.js project, so I'm using the npm package here: https://www.npmjs.com/package/livesplit-core/

I am able to successfully instantiate a `Timer`, but the `current_time` method does not appear to be bound, and does not appear to be accessible via the npm package. Have I perhaps overlooked something? Is there another way I should be reading the current time from a `Timer` instance?

Thanks!
Alex

**Comment by CryZe** [comment]
Hey Alex,

pretty cool that you are checking out livesplit-core. NodeCg should be a really good fit for livesplit-core. It seems like we indeed forgot to expose the current time in the timer object. But that's because we actually never needed it. And for good reason, usually you want to use the actual components instead of querying information manually from the timer object. All the components are written to be entirely UI independent. They just provide state objects (JSON in case of the JS version) that you can query and you can then choose to visualize them in whatever way. So that should work really well with NodeCg, as that also works similarly afaik. If you have further questions about how to use the components and co. then it's probably easier if you hit me up on Discord (CryZe#5623) (or Twitter DMs I guess).

I'll add those missing accessors regardless, as those might still be useful.
